### PR TITLE
Hadika Malik/Feature/Order type

### PR DESCRIPTION
**Pull request by HadikaMalik**
Feature order type has been added. 
It works well but the tests which were written for Restaurant fail.

### CODE REVIEW

**Comment by PERicci** [comment]
> It works well but the tests which were written for Restaurant fail.

It is happening because the test is finding more than one element with the text 'Add', so it does not know which one has been clicked.
I recommend you to add a data-testid property to the element and change the test to search for the element with getByTestId.
If you have any difficulty, don't worry. I can show you how to solve this in our class on Saturday.

**Review by PERicci — APPROVED** [review]
All requirements have been met, with clean code and on time.

**Comment by eliza-an** [comment]
> > It works well but the tests which were written for Restaurant fail.
> 
> It is happening because the test is finding more than one element with the text 'Add', so it does not know which one has been clicked. I recommend you to add a data-testid property to the element and change the test to search for the element with getByTestId. If you have any difficulty, don't worry. I can show you how to solve this in our class on Saturday.

Yes, I explained this in an earlier code review, please have a look there if you need further help with this!

**Review by eliza-an — COMMENTED** [review]
this works well, but you must write individual test for each order independently as per the instructions as well as 
add to the test description
image

**Pull request merged**
